services:

  mongodb:
    image: mongodb:v1
    container_name: mongodb

  catalouge:
    image: catalouge:v1
    container_name: catalouge
    depends_on:
      - mongodb
  redis:
    image: radis:7.0
    container_name: radis
  mysql:
    image: mysql:v1
    container_name: mysql
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_USER: roboshop123
  user:
    image: user:v1
    container_name: user
    depends_on:
      - mongodb
      - redis
  cart:
    image: cart:v1
    container_name: cart
    depends_on:
      - redis 
      - catalouge
  shipping:
    image: shipping:v1
    container_name: shipping
    deponds_on:
      - mysql
      - cart
  payment:
    image: payment:v1
    container_name: payment
    depends_on:
      - rabbitmq
      - cart
      - user
  frontend:
    image: frontend:v1
    container_name: frontend
    ports: 
      - 80:80
    depends_on:
      - catalouge
      - user
      - cart
      - shipping
      - payment
                           


networks:
  default:
    driver: bridge
    name: roboshop
    external: false